# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Example hwloc Function
#'
#' This function provides a simple introduction and overview of \code{hwloc}
#' by printing some diagnostics to the standard output
#' @return Nothing is returned, the function is invoked for the side effect of
#' displaying to the standard output.
hwlocExample <- function() {
    invisible(.Call(`_RcppHwloc_hwlocExample`))
}

